name: build

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        pg: [14, 13]
    name: PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    steps:
      - uses: adjust/pg-ext-actions/pg-setup@master
        with:
          version: ${{ matrix.pg }}
      - uses: actions/checkout@v2
      - uses: adjust/pg-ext-actions/build-check@master
